### ISSUE TITLE
Time format

### ISSUE THREAD

**Issue by usachovartem** [shevchuknine/pyramid-game-dev#19]
Please update time format (remove seconds)
![image](https://user-images.githubusercontent.com/37213773/43204637-1e1fb676-902a-11e8-8fe1-5d116b55ff77.png)

**Comment by shevchuknine** [comment]
Need to change formatting of date ftom `.toLocaleTimeString()` to `getHours() + getMinutes()`

**Comment by shevchuknine** [comment]
https://github.com/shevchuknine/pyramid-game-dev/pull/23
